import os

DATABASE_URI = "sqlite:////tmp/foo.db"
SECRET_KEY = 'hq0wt)+6vb18zmf=q%9ad&!=(7k24c&*io)^v6@$#u_*i#(%qb'
FLASK_DEBUG = True

SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = False

API_URL = os.getenv('API_URL')

WTF_CSRF_ENABLED = True
OPENAPI_URL_PREFIX = '/api/docs/'
OPENAPI_SWAGGER_UI_PATH = '/'
OPENAPI_SWAGGER_UI_VERSION = '3.22.0'
